name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GOVERSION: 1.17

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          goos: windows
        - os: ubuntu-latest
          goos: linux
        - os: macos-latest
          goos: darwin
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go ${{ env.GOVERSION }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^${{ env.GOVERSION }}'
    - name: test
      run: GOOS=${{ matrix.goos }} go test ./... -cover
