name: ci

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  GOVERSION: 1.17

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          goos: windows
          lint: true
        - os: ubuntu-latest
          goos: linux
          lint: true
        - os: macos-latest
          goos: darwin
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go ${{ env.GOVERSION }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^${{ env.GOVERSION }}'
    - name: test
      run: GOOS=${{ matrix.goos }} go test ./... -cover

  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        - os: windows-latest
          goos: windows
        - os: ubuntu-latest
          goos: linux
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: install go ${{ env.GOVERSION }}
      uses: actions/setup-go@v2.1.4
      with:
        go-version: '^${{ env.GOVERSION }}'
    - name: lint
      if: ${{ matrix.lint == 'true' }}
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        only-new-issues: true
        skip-go-installation: true

  check:
    runs-on: ubuntu-latest
    needs:
    - lint
    - test
    steps:
    - name: check
      run: echo -e "\e[32mSuccess\e[0m"
